apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: swiss-army-knife
spec:
  selector:
    matchLabels:
      app: swiss-army-knife
  template:
    metadata:
      labels:
        app: swiss-army-knife
    spec:
      containers:
        - image: utkuozdemir/swiss-army-knife:v0.3.0
          name: swiss-army-knife
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      terminationGracePeriodSeconds: 0
